
version: '2'

services:
  question-book:
    user: root
    image: ${QUESTION_BOOK_IMAGE}
    container_name: ${QUESTION_BOOK_CONTAINER}
    tmpfs: /tmp
    build:
      context: app
      args:
        - PORT=${QUESTION_BOOK_PORT}
    ports:
      - ${QUESTION_BOOK_PORT}:${QUESTION_BOOK_PORT}
