source "https://rubygems.org"

gem "sinatra"
gem "thin"

group :development, :test do
  gem 'rake'
  gem 'json'
end

group :test do
  gem 'minitest', require: 'minitest/autorun'
  gem 'rack-test', require: 'rack/test'
end
